azs:
- name: z1
vm_types:
- name: default
  cloud_properties:
    ephemeral_disk:
      size: 1024
      type: gp2
disk_types:
- name: default
  disk_size: 1024
compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  vm_type: default
networks:
- name: default
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.0.0/30
    reserved:
    - 10.244.0.1
  - cloud_properties:
      name: random
    range: 10.244.0.4/30
    reserved:
    - 10.244.0.5
  - cloud_properties:
      name: random
    range: 10.244.0.8/30
    reserved:
    - 10.244.0.9
  - cloud_properties:
      name: random
    range: 10.244.0.12/30
    reserved:
    - 10.244.0.13
