name: cockroachdb

director_uuid: __REPLACE_WITH_DIRECTORS_UUID__

releases:
  - name: cockroachdb
    version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-300000
  update_watch_time: 1000-300000

instance_groups:
- name: cockroachdb
  instances: 3 # this number should always be odd (quorum)
  azs: [z1]
  jobs:
  - name: cockroachdb
    release: cockroachdb
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default
  provides:
    cockroach: {from: cockroachdb}
  consumes:
    cockroach: {from: cockroachdb}
