name: cockroachdb

director_uuid: __REPLACE_WITH_DIRECTORS_UUID__

releases:
  - name: cockroachdb
    version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- name: cockroachdb
  instances: 3 # this number should always be odd (quorum)
  azs: [ z1, z2, z3, z4 ]
  jobs:
  - name: cockroachdb
    release: cockroachdb
  vm_type: t2.micro
  stemcell: default
  networks:
  - name: private
  provides:
    cockroach: {from: cockroachdb}
  consumes:
    cockroach: {from: cockroachdb}
